### ISSUE TITLE
Local backup and linux support

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [nyagami/lnreader-rs#1]
Is there any way to implement this backup that backs up everything as a local backup as well in lnreader? I would prefer to get a local backup on my phone and use syncthing to sync to my linux machine.

**Comment by nyagami** [comment]
- what do you mean by local backup
- if you cant run .exe on linux, follow these steps:
  + clone project
  + `pip install -r requirements.txt`
  + `pdm server <ipv4> <port>`

**Comment by nyagami** [comment]
wait hold a min, you should create issue in https://github.com/LNReader/remote-service

**Comment by 1-minute-to-midnight** [comment]
I have opened the issue there now: https://github.com/LNReader/remote-service/issues/5
